### PR TITLE
Feature #57 Add settings

### PR DESCRIPTION
**Pull request by 0xbaadf00d**
Add settings (#57) to allow filter customization without using class inheritance.

**application.conf**
```
play.filters {
  compressor {
    html {
      preserveLineBreaks = true
      removeComments = true
      removeIntertagSpaces = false
      removeHttpProtocol = true
      removeHttpsProtocol = true
    }

    xml {
      removeComments = true
      removeIntertagSpaces = false
    }
  }
}
```

### CODE REVIEW

**Comment by 0xbaadf00d** [comment]
@akkie Your master branch seems bugged: all unit tests for Gzip fail (tested with the command `sbt test` on Windows 10 64 bit with Java 8u102 / scala 2.11.8.400 / sbt 0.13.11.2).

Edit 1: @akkie  relative to the previous comment, Travis also fail on Gzip unit tests

**Comment by akkie** [comment]
Great! Please could you squash the both commits into one?

**Comment by akkie** [comment]
Maybe you could also document this feature in the readme?

**Comment by 0xbaadf00d** [comment]
Ok I will edit README. You could squash commit by checking option when you click on Merge button on Github (https://github.com/blog/2141-squash-your-commits).

**Comment by akkie** [comment]
Great! Thanks!

**Comment by eximius313** [comment]
@akkie will you release a new version?

**Comment by akkie** [comment]
Yes, in the next few days. In the meantime you can use `sbt publish-local`.

**Comment by akkie** [comment]
0.6.3 is out

**Comment by eximius313** [comment]
awesome!

**Pull request merged**
